### ISSUE TITLE
Automatic detection of (un-)successful deploy

### ISSUE THREAD

**Issue by uruuru** [OpenKieler/elkgraph-web#5]
We use the KIELER project's bamboo to trigger an automatic deploy of the application on one of their [servers](https://rtsys.informatik.uni-kiel.de/elklive/). Currently, this _trigger event_ always succeeds. Instead it should fail if the build fails such that bamboo notifies the persons responsible for the failure.

**Comment by uruuru** [comment]
@saftigall is this in effect? If so, who get's notified?

**Comment by saftigall** [comment]
@uruuru Yes, it's up and running. I just added you to the notification receipents (Failed Builds And First Successful).

**Comment by uruuru** [comment]
Thanks.

**Comment by uruuru** [comment]
Is it successful at the moment? It doesn't seem to pick up the latest version. Which mail did you add? @saftigall
